# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run Tests
          command: python -m unittest discover 'test_app.py'

workflows:
  version: 2
  build:
    jobs:
      - build

